# Generated by Django 3.2.6 on 2021-08-08 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_chef_handle', models.CharField(max_length=150)),
                ('hacker_rank_handle', models.CharField(blank=True, max_length=150)),
                ('hacker_earth_handle', models.CharField(blank=True, max_length=150)),
                ('code_forces_handle', models.CharField(blank=True, max_length=150)),
                ('code_chef_score', models.IntegerField(default=0)),
                ('hacker_rank_score', models.IntegerField(blank=True)),
                ('hacker_earth_score', models.IntegerField(blank=True)),
                ('code_forces_score', models.IntegerField(blank=True)),
                ('vardhaman_mail_id', models.EmailField(max_length=254)),
                ('roll_no', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
