# Generated by Django 3.2.6 on 2021-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code_chef_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
