# Generated by Django 3.2.6 on 2021-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_vardhaman_mail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
