# Generated by Django 3.2.6 on 2021-08-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='ECE', max_length=4),
            preserve_default=False,
        ),
    ]
